// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtJYMxqVsjL-qouRY1e_k7rGmpkBbNf8Y',
    appId: '1:39328032293:web:6d25e47d9858131c6b81cc',
    messagingSenderId: '39328032293',
    projectId: 'bu-connect-1',
    authDomain: 'bu-connect-1.firebaseapp.com',
    storageBucket: 'bu-connect-1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnMxLiHeU_OXWqtyulp-0hE3Ty-ft5yCo',
    appId: '1:39328032293:android:d5566214fec39ab96b81cc',
    messagingSenderId: '39328032293',
    projectId: 'bu-connect-1',
    storageBucket: 'bu-connect-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:39328032293:ios:c8d34b855f6b86216b81cc',
    messagingSenderId: '39328032293',
    projectId: 'bu-connect-1',
    storageBucket: 'bu-connect-1.appspot.com',
    iosBundleId: 'com.example.buConnect',
  );
}
